/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Creator, Spot, Guide } from "./types";

export const CREATORS: Creator[] = [
  {
    id: "sofia",
    name: "Sofia Fernandes",
    handle: "@sofi_escapes",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    bio: "Unearthing local vinyl spots, aesthetic matcha dens, and cozy rainy canopy hideaways. No gatekeeping, just pure vibes.",
    specialty: "Matcha & Melodies",
    vibeTitle: "Sunset General",
    followers: 42800,
    aura: 8430,
    discoveriesCount: 14,
    badges: ["Hidden Gem Hunter", "Local Guide"],
    topPlacesShared: ["The Minimalist Whisk", "Spin & Sip Records + Bar"]
  },
  {
    id: "ananya",
    name: "Ananya Mehta",
    handle: "@ananya_codes_vibes",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200",
    bio: "Full-time UI designer, part-time vintage thrifter and high-contrast coffee-spot locator. Seeking extreme natural light & quiet rooms.",
    specialty: "Thrift & Espresso",
    vibeTitle: "Chief Aesthetic Officer",
    followers: 12400,
    aura: 3900,
    discoveriesCount: 6,
    badges: ["Weekend Explorer", "Thrift Expert"],
    topPlacesShared: ["Unruly Threads Thrift Shop", "Room 101 Book Nook"]
  },
  {
    id: "marcus",
    name: "Marcus Lee",
    handle: "@m_lee_travels",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    bio: "Seeking hyper-local culture, secret spice dens, and record stores that feel like a Y2K fever dream. On a constant search for the ultimate street chaat.",
    specialty: "Spices & Playlists",
    vibeTitle: "Main Character Energy",
    followers: 9540,
    aura: 5120,
    discoveriesCount: 9,
    badges: ["Food Expert", "Weekend Explorer"],
    topPlacesShared: ["Marine Sunset Aura", "Monsoon Shadows Canopy"]
  }
];

export const SPOTS: Spot[] = [
  {
    id: "spot-1",
    name: "The Minimalist Whisk",
    city: "Bangalore",
    neighborhood: "Indiranagar",
    category: "Cafe",
    vibes: ["Aesthetic AF", "Matcha Heaven", "Plugs Everywhere", "Quiet Slay"],
    priceRange: "Comfy Enough",
    address: "12th Main Rd, Indiranagar, Bengaluru, KA",
    coords: { lat: 12.9715987, lng: 77.641234 },
    imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=600",
    description: "The absolute zenith of clean lines and ceremonial-grade iced matcha. Flawless Japandi timber interiors, endless Monstera leaf shadowplay, and lo-fi beats that are actually calibrated to boost your dopamine.",
    whyGo: "Their whisking technique is next level - zero lumps, fully organic, silky smooth. It belongs in a glass museum.",
    bestTime: "Tuesday Morning for extreme quiet session, or 5:15 PM for golden shadows on the concrete wall.",
    whatToOrder: "Ceremonial Iced Lavender Matcha Espresso Float & Vegan Almond Croissant",
    stats: {
      rating: 9.6,
      matchaScore: "11/10 (Ceremonial)",
      wifiClass: "Zoomer Speed (300 Mbps)",
      goldenHour: "5:00 PM - 6:00 PM",
      noiseLevel: "Whisper Mode & Soft Synth",
    },
    creatorId: "sofia",
    gatekept: false,
    votesHype: 342,
    votesMid: 12,
    onlyLocalsKnow: false,
    touristTrapWarning: "The matcha corner across 12th Main is a full tourist trap franchise using culinary grade leaves with sugar syrups, avoid them!",
    nearbyDiscoveries: ["spot-2"]
  },
  {
    id: "spot-2",
    name: "Spin & Sip Records + Bar",
    city: "Mumbai",
    neighborhood: "Bandra West",
    category: "Vinyl Bar",
    vibes: ["Vinyl Only", "Y2K Fever Dream", "Mood Lighting", "Secret Entrance"],
    priceRange: "Treat Yourself",
    address: "Perry Road, Off Hill Road, Bandra West, Mumbai, MH",
    coords: { lat: 19.055812, lng: 72.829145 },
    imageUrl: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&q=80&w=600",
    description: "A cozy underground listening sanctuary hidden behind a faux dry-cleaners storefront. Handcrafted wooden acoustic horns, thousands of rare Japanese jazz fusion records playing in perfect analog quality.",
    whyGo: "Absolute audiophile heaven. Sit on the velvet loungers under red neons and let your mind hover in pristine soundscapes.",
    bestTime: "Thursday nocturnal sessions starting at 9:30 PM (Real ones arrive early).",
    whatToOrder: "Cold Brew Highball & Smoked Salmon Bites",
    stats: {
      rating: 9.8,
      matchaScore: "Not Served",
      wifiClass: "Cellular Only (Put your phone away)",
      goldenHour: "Dim Lit Neon (Always Night)",
      noiseLevel: "Analog Warmth (High Fidelity)",
    },
    creatorId: "sofia",
    gatekept: true,
    votesHype: 512,
    votesMid: 24,
    onlyLocalsKnow: true,
    touristTrapWarning: "Do NOT hand over your keys to random guys standing outside claiming they do valet parking for the bar; search for the public civic bay nearby.",
    nearbyDiscoveries: ["spot-5", "spot-7"]
  },
  {
    id: "spot-3",
    name: "Unruly Threads Thrift Shop",
    city: "Delhi",
    neighborhood: "Hauz Khas Village",
    category: "Thrift Store",
    vibes: ["Y2K Vintage", "Streetwear Holy Grail", "Absolute Banger Pricing", "Curated Heat"],
    priceRange: "Broke Bestie",
    address: "Hauz Khas Village, Lane 4, New Delhi, DL",
    coords: { lat: 28.552912, lng: 77.195232 },
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&q=80&w=600",
    description: "Packed with curated 90s windbreakers, oversized utility overalls, cargo pants, and rare band tees. It's a goldmine of thrift treasures carefully sourced and dry-cleaned. They drop new crates every Friday morning.",
    whyGo: "No fast fashion garbage. Everything in here is unique, certified vintage, and priced to save your wallet.",
    bestTime: "Friday morning 10:00 AM straight after a crate drop.",
    whatToOrder: "90s Oversized Leather Racer Jackets or Y2K Baggy Cargos",
    stats: {
      rating: 9.3,
      wifiClass: "Standard (Focus on digging)",
      goldenHour: "Sunlight hitting the vintage racks",
      noiseLevel: "90s Hip Hop beats on repeat",
    },
    creatorId: "ananya",
    gatekept: false,
    votesHype: 289,
    votesMid: 9,
    onlyLocalsKnow: false,
    touristTrapWarning: "Avoid vendors trying to lure you into 'rooftop cafes with taj views' near Hauz Khas entry. They demand ₹1000 cover charges for bad canned juices.",
    nearbyDiscoveries: ["spot-6"]
  },
  {
    id: "spot-4",
    name: "Monsoon Shadows Canopy",
    city: "Goa",
    neighborhood: "Assagao",
    category: "Cafe",
    vibes: ["Deep Jungle Vibe", "Rainy Day Sanctuary", "Typerwriter Aesthetic", "Plugs Everywhere"],
    priceRange: "Treat Yourself",
    address: "Boutique Lane, Assagao, Goa, GA",
    coords: { lat: 15.592834, lng: 73.784912 },
    imageUrl: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&q=80&w=600",
    description: "An open-air pavilion nestled inside thick jungle foliage. Raindrops bounce off giant elephant-ear leaves while you sit on bespoke rattan chairs. Perfect coffee, hand-poured single origins, and typewriters available for borrowing.",
    whyGo: "For experiencing spectacular Goan rainstorms while listening to live acoustic synth performances.",
    bestTime: "3:00 PM on a wet afternoon for peak melancholic cozy focus.",
    whatToOrder: "Goan Spiced Coconut Cortado & Sourdough Eggs Benedict",
    stats: {
      rating: 9.7,
      matchaScore: "8.5/10 (Decent Whisk)",
      wifiClass: "Satellite Internet (Unbreakable)",
      goldenHour: "4:00 PM Canopy Light Show",
      noiseLevel: "Pitter Patter of Rain + Soft Chords",
    },
    creatorId: "marcus",
    gatekept: true,
    votesHype: 196,
    votesMid: 4,
    onlyLocalsKnow: true,
    touristTrapWarning: "The taxi stand outside Assagao circle will ask for ₹1200 minimum. Use reliable app-ride connections or local scooter leases instead.",
    nearbyDiscoveries: []
  },
  {
    id: "spot-5",
    name: "Marine Sunset Aura",
    city: "Mumbai",
    neighborhood: "Marine Drive",
    category: "Sunset Spot",
    vibes: ["Free Dot Org", "Golden Hour Glow Up", "Chai Companions", "Real Ones Know"],
    priceRange: "Broke Bestie",
    address: "Marine Drive Promanade, Netaji Subhash Chandra Bose Rd, Mumbai",
    coords: { lat: 18.943912, lng: 72.823902 },
    imageUrl: "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&q=80&w=600",
    description: "The concrete tetra-pods that shield the coastline are local hotspots for late afternoon therapy. Sit with hundreds of real ones, listen to buskers, sip hot cutting chai, and watch the orange sun sink straight into the Arabian sea.",
    whyGo: "You cannot buy a better feeling. The absolute queen of sunset places, completely free.",
    bestTime: "6:15 PM in the summer, grab your spot by 5:45.",
    whatToOrder: "Hot Ginger Cutting Chai from a mobile seller & mineral water",
    stats: {
      rating: 9.9,
      wifiClass: "5G Everywhere",
      goldenHour: "6:00 PM - 6:45 PM Gold Rush",
      noiseLevel: "Sea Breezes, Chatters & Acoustic Guitar",
    },
    creatorId: "marcus",
    gatekept: false,
    votesHype: 840,
    votesMid: 15,
    onlyLocalsKnow: false,
    touristTrapWarning: "Don't fall for standard selfie vendors charging ₹100 per snapshot on Polaroids - they often fade in 2 days. Snap with your premium phone camera instead for free.",
    nearbyDiscoveries: ["spot-2", "spot-7"]
  },
  {
    id: "spot-6",
    name: "Room 101 Book Nook",
    city: "Delhi",
    neighborhood: "Hauz Khas Village",
    category: "Bookstore",
    vibes: ["Quiet Slay", "Aura Healing", "Smells Like Ink", "Vintage Book Stack"],
    priceRange: "Broke Bestie",
    address: "Outer Ring, Block C, Hauz Khas, New Delhi",
    coords: { lat: 28.549213, lng: 77.200109 },
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&q=80&w=600",
    description: "A dusty, multi-floored independent library and coffee hatch. Zero noise tolerated. Shelves extend to high ceilings, housing vintage out-of-print poetry, classic paperbacks, and indie graphic design zines.",
    whyGo: "If you want to read in complete solitude with single-origin pour overs and absolute vintage quietness.",
    bestTime: "Weekdays 11:00 AM - 2:00 PM for ghost-town quietness.",
    whatToOrder: "Sumatra Single Origin Pour Over & Sea Salt Salted Caramel Tart",
    stats: {
      rating: 9.4,
      wifiClass: "Silent Zone (No Zoom calls)",
      goldenHour: "2:00 PM through stained glass window",
      noiseLevel: "Dead Silent (Page turns only)",
    },
    creatorId: "ananya",
    gatekept: true,
    votesHype: 231,
    votesMid: 8,
    onlyLocalsKnow: true,
    touristTrapWarning: "Influencers often try to do full apparel shoots in the aisles; the library owners will hand you a strict fine. Treat this as a sacred silence zone fr fr.",
    nearbyDiscoveries: ["spot-3"]
  },
  {
    id: "spot-7",
    name: "Napean Sunset Cliff",
    city: "Mumbai",
    neighborhood: "Bandra West",
    category: "Sunset Spot",
    vibes: ["Aesthetic AF", "Ocean Spray", "Gatekept", "Zero Crowds"],
    priceRange: "Broke Bestie",
    address: "Rocky Edge Promenade, Mumbai",
    coords: { lat: 18.955012, lng: 72.802102 },
    imageUrl: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&q=80&w=600",
    description: "A narrow rocky pathway off the main road that opens up to a direct ocean cliff. Zero tourists, zero vendor stalls. Just pure cliff shadows, splashing white currents, and direct view of the horizon.",
    whyGo: "To disconnect and play your melancholy playlists with ocean foam right beneath you.",
    bestTime: "6:00 PM, grab a seat on the flat dry boulder.",
    whatToOrder: "Pack your own flask and audio earbuds.",
    stats: {
      rating: 9.7,
      wifiClass: "Spotty (Disconnect fr)",
      goldenHour: "5:50 PM - 6:30 PM",
      noiseLevel: "Wave crashes (Loud & Healing)",
    },
    creatorId: "sofia",
    gatekept: true,
    votesHype: 174,
    votesMid: 2,
    onlyLocalsKnow: true,
    touristTrapWarning: "Avoid walking onto the wet dark moss-covered slopes near the shelf edge, the rock drops are sudden and the sea current is extremely violent.",
    nearbyDiscoveries: ["spot-2"]
  }
];

export const GUIDES: Guide[] = [
  {
    id: "guide-1",
    title: "Indiranagar Cafe Hop: Absolute Zero Gatekeeping Version",
    description: "My personal map of actual clean-lines aesthetic cafes. We're dodging commercial chains entirely. Just high-grade matcha, crazy fast wifi, and pastries that make you emotional fr.",
    coverUrl: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600",
    creatorId: "sofia",
    spots: ["spot-1", "spot-4"],
    duration: "One Afternoon (3-4 Hours)",
    totalCostBudget: "Low Key Slay (~₹800)",
    tags: ["Matcha Hop", "Aesthetic Hunt", "Cafe Coziness"]
  },
  {
    id: "guide-2",
    title: "The Ultimate Audiophile & Golden Aura Date Map in Bandra",
    description: "Start behind a proxy storefront hidden vintage room listening to rare jazz grooves, then exit in the nick of time to walk down to rock cliffs for direct horizon views. Instant high-vibe date winner.",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600",
    creatorId: "sofia",
    spots: ["spot-2", "spot-7"],
    duration: "Evening (6:00 PM - 10:00 PM)",
    totalCostBudget: "Fancy Outing (~₹2500)",
    tags: ["Music Lovers", "Sunset Match", "Romantic Aura"]
  }
];
